import type { Stock } from './types';

export const INITIAL_STOCKS: Stock[] = [
  {
    id: 'aapl',
    ticker: 'AAPL',
    name: 'Apple Inc.',
    sector: 'technology',
    description: 'Consumer electronics, software, and services company known for iPhone, Mac, and a growing services ecosystem.',
    basePrice: 192,
    currentPrice: 192,
    priceHistory: [{ turn: 0, price: 192 }],
    volatility: 0.22,
    marketCap: 'mega',
    dividendYield: 0.005,
    beta: 1.2,
    splitMultiplier: 1,
  },
  {
    id: 'msft',
    ticker: 'MSFT',
    name: 'Microsoft Corp.',
    sector: 'technology',
    description: 'Enterprise software, cloud computing (Azure), and productivity tools giant.',
    basePrice: 415,
    currentPrice: 415,
    priceHistory: [{ turn: 0, price: 415 }],
    volatility: 0.2,
    marketCap: 'mega',
    dividendYield: 0.008,
    beta: 1.1,
    splitMultiplier: 1,
  },
  {
    id: 'goog',
    ticker: 'GOOG',
    name: 'Alphabet Inc.',
    sector: 'technology',
    description: 'Parent of Google, dominating search, digital advertising, and cloud with AI investments.',
    basePrice: 155,
    currentPrice: 155,
    priceHistory: [{ turn: 0, price: 155 }],
    volatility: 0.28,
    marketCap: 'mega',
    dividendYield: 0.0,
    beta: 1.15,
    splitMultiplier: 1,
  },
  {
    id: 'meta',
    ticker: 'META',
    name: 'Meta Platforms',
    sector: 'technology',
    description: 'Social media conglomerate (Facebook, Instagram, WhatsApp) investing heavily in AI and metaverse.',
    basePrice: 500,
    currentPrice: 500,
    priceHistory: [{ turn: 0, price: 500 }],
    volatility: 0.35,
    marketCap: 'mega',
    dividendYield: 0.004,
    beta: 1.3,
    splitMultiplier: 1,
  },
  {
    id: 'crm',
    ticker: 'CRM',
    name: 'Salesforce Inc.',
    sector: 'technology',
    description: 'Cloud-based CRM and enterprise software leader in customer relationship management.',
    basePrice: 275,
    currentPrice: 275,
    priceHistory: [{ turn: 0, price: 275 }],
    volatility: 0.3,
    marketCap: 'large',
    dividendYield: 0.006,
    beta: 1.25,
    splitMultiplier: 1,
  },
  {
    id: 'nvda',
    ticker: 'NVDA',
    name: 'NVIDIA Corp.',
    sector: 'semiconductors',
    description: 'GPU and AI chip leader powering data centers, gaming, and autonomous vehicles.',
    basePrice: 880,
    currentPrice: 880,
    priceHistory: [{ turn: 0, price: 880 }],
    volatility: 0.45,
    marketCap: 'mega',
    dividendYield: 0.001,
    beta: 1.7,
    splitMultiplier: 1,
  },
  {
    id: 'tsm',
    ticker: 'TSM',
    name: 'Taiwan Semiconductor',
    sector: 'semiconductors',
    description: 'World largest dedicated independent semiconductor foundry manufacturing chips for global tech giants.',
    basePrice: 155,
    currentPrice: 155,
    priceHistory: [{ turn: 0, price: 155 }],
    volatility: 0.35,
    marketCap: 'mega',
    dividendYield: 0.02,
    beta: 1.4,
    splitMultiplier: 1,
  },
  {
    id: 'amd',
    ticker: 'AMD',
    name: 'Advanced Micro Devices',
    sector: 'semiconductors',
    description: 'Semiconductor company competing in CPUs, GPUs, and data center processors.',
    basePrice: 175,
    currentPrice: 175,
    priceHistory: [{ turn: 0, price: 175 }],
    volatility: 0.42,
    marketCap: 'large',
    dividendYield: 0.0,
    beta: 1.5,
    splitMultiplier: 1,
  },
  {
    id: 'avgo',
    ticker: 'AVGO',
    name: 'Broadcom Inc.',
    sector: 'semiconductors',
    description: 'Semiconductor and infrastructure software company serving data centers and networking.',
    basePrice: 1350,
    currentPrice: 1350,
    priceHistory: [{ turn: 0, price: 1350 }],
    volatility: 0.3,
    marketCap: 'mega',
    dividendYield: 0.015,
    beta: 1.3,
    splitMultiplier: 1,
  },
  {
    id: 'qcom',
    ticker: 'QCOM',
    name: 'Qualcomm Inc.',
    sector: 'semiconductors',
    description: 'Wireless technology and mobile chip leader powering 5G and next-gen connectivity.',
    basePrice: 170,
    currentPrice: 170,
    priceHistory: [{ turn: 0, price: 170 }],
    volatility: 0.32,
    marketCap: 'large',
    dividendYield: 0.022,
    beta: 1.25,
    splitMultiplier: 1,
  },
  {
    id: 'jnj',
    ticker: 'JNJ',
    name: 'Johnson & Johnson',
    sector: 'healthcare',
    description: 'Diversified healthcare giant in pharmaceuticals, medical devices, and consumer health products.',
    basePrice: 160,
    currentPrice: 160,
    priceHistory: [{ turn: 0, price: 160 }],
    volatility: 0.12,
    marketCap: 'mega',
    dividendYield: 0.03,
    beta: 0.6,
    splitMultiplier: 1,
  },
  {
    id: 'unh',
    ticker: 'UNH',
    name: 'UnitedHealth Group',
    sector: 'healthcare',
    description: 'Largest US health insurer and healthcare services company through Optum.',
    basePrice: 530,
    currentPrice: 530,
    priceHistory: [{ turn: 0, price: 530 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.014,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'pfe',
    ticker: 'PFE',
    name: 'Pfizer Inc.',
    sector: 'healthcare',
    description: 'Global pharmaceutical company known for vaccines, oncology, and innovative therapies.',
    basePrice: 28,
    currentPrice: 28,
    priceHistory: [{ turn: 0, price: 28 }],
    volatility: 0.25,
    marketCap: 'large',
    dividendYield: 0.06,
    beta: 0.65,
    splitMultiplier: 1,
  },
  {
    id: 'mrk',
    ticker: 'MRK',
    name: 'Merck & Co.',
    sector: 'healthcare',
    description: 'Pharmaceutical company with leading oncology (Keytruda) and vaccine franchises.',
    basePrice: 125,
    currentPrice: 125,
    priceHistory: [{ turn: 0, price: 125 }],
    volatility: 0.2,
    marketCap: 'mega',
    dividendYield: 0.022,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'abbv',
    ticker: 'ABBV',
    name: 'AbbVie Inc.',
    sector: 'healthcare',
    description: 'Biopharmaceutical company with immunology, oncology, and neuroscience portfolio.',
    basePrice: 170,
    currentPrice: 170,
    priceHistory: [{ turn: 0, price: 170 }],
    volatility: 0.22,
    marketCap: 'mega',
    dividendYield: 0.038,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'amgn',
    ticker: 'AMGN',
    name: 'Amgen Inc.',
    sector: 'biotech',
    description: 'One of the world largest independent biotechnology companies focused on serious illnesses.',
    basePrice: 290,
    currentPrice: 290,
    priceHistory: [{ turn: 0, price: 290 }],
    volatility: 0.24,
    marketCap: 'large',
    dividendYield: 0.032,
    beta: 0.75,
    splitMultiplier: 1,
  },
  {
    id: 'gild',
    ticker: 'GILD',
    name: 'Gilead Sciences',
    sector: 'biotech',
    description: 'Biopharmaceutical company specializing in antivirals, HIV, and oncology treatments.',
    basePrice: 75,
    currentPrice: 75,
    priceHistory: [{ turn: 0, price: 75 }],
    volatility: 0.3,
    marketCap: 'large',
    dividendYield: 0.04,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'biib',
    ticker: 'BIIB',
    name: 'Biogen Inc.',
    sector: 'biotech',
    description: 'Biotechnology company focused on neuroscience, multiple sclerosis, and Alzheimer therapies.',
    basePrice: 240,
    currentPrice: 240,
    priceHistory: [{ turn: 0, price: 240 }],
    volatility: 0.38,
    marketCap: 'mid',
    dividendYield: 0.0,
    beta: 0.85,
    splitMultiplier: 1,
  },
  {
    id: 'vrtx',
    ticker: 'VRTX',
    name: 'Vertex Pharmaceuticals',
    sector: 'biotech',
    description: 'Biotech leader in cystic fibrosis treatments with a growing pipeline in pain and gene editing.',
    basePrice: 440,
    currentPrice: 440,
    priceHistory: [{ turn: 0, price: 440 }],
    volatility: 0.28,
    marketCap: 'large',
    dividendYield: 0.0,
    beta: 0.8,
    splitMultiplier: 1,
  },
  {
    id: 'mrna',
    ticker: 'MRNA',
    name: 'Moderna Inc.',
    sector: 'biotech',
    description: 'mRNA platform company leveraging technology for vaccines, oncology, and rare diseases.',
    basePrice: 170,
    currentPrice: 170,
    priceHistory: [{ turn: 0, price: 170 }],
    volatility: 0.5,
    marketCap: 'mid',
    dividendYield: 0.0,
    beta: 1.4,
    splitMultiplier: 1,
  },
  {
    id: 'xom',
    ticker: 'XOM',
    name: 'Exxon Mobil',
    sector: 'energy',
    description: 'One of the world largest integrated oil and gas companies with upstream, downstream, and chemical operations.',
    basePrice: 108,
    currentPrice: 108,
    priceHistory: [{ turn: 0, price: 108 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.035,
    beta: 0.8,
    splitMultiplier: 1,
  },
  {
    id: 'cvx',
    ticker: 'CVX',
    name: 'Chevron Corp.',
    sector: 'energy',
    description: 'Integrated energy company engaged in petroleum, chemicals, and increasingly renewable energy.',
    basePrice: 160,
    currentPrice: 160,
    priceHistory: [{ turn: 0, price: 160 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.04,
    beta: 0.8,
    splitMultiplier: 1,
  },
  {
    id: 'slb',
    ticker: 'SLB',
    name: 'Schlumberger',
    sector: 'energy',
    description: 'World largest oilfield services company providing technology for reservoir characterization and drilling.',
    basePrice: 50,
    currentPrice: 50,
    priceHistory: [{ turn: 0, price: 50 }],
    volatility: 0.25,
    marketCap: 'large',
    dividendYield: 0.016,
    beta: 1.0,
    splitMultiplier: 1,
  },
  {
    id: 'enph',
    ticker: 'ENPH',
    name: 'Enphase Energy',
    sector: 'energy',
    description: 'Solar microinverter and energy storage systems manufacturer for residential and commercial markets.',
    basePrice: 120,
    currentPrice: 120,
    priceHistory: [{ turn: 0, price: 120 }],
    volatility: 0.45,
    marketCap: 'mid',
    dividendYield: 0.0,
    beta: 1.5,
    splitMultiplier: 1,
  },
  {
    id: 'fslr',
    ticker: 'FSLR',
    name: 'First Solar',
    sector: 'energy',
    description: 'American solar panel manufacturer specializing in thin-film technology for utility-scale projects.',
    basePrice: 270,
    currentPrice: 270,
    priceHistory: [{ turn: 0, price: 270 }],
    volatility: 0.38,
    marketCap: 'mid',
    dividendYield: 0.0,
    beta: 1.3,
    splitMultiplier: 1,
  },
  {
    id: 'jpm',
    ticker: 'JPM',
    name: 'JPMorgan Chase',
    sector: 'financials',
    description: 'Largest US bank by assets, offering investment banking, commercial banking, and asset management.',
    basePrice: 200,
    currentPrice: 200,
    priceHistory: [{ turn: 0, price: 200 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.024,
    beta: 1.1,
    splitMultiplier: 1,
  },
  {
    id: 'v',
    ticker: 'V',
    name: 'Visa Inc.',
    sector: 'financials',
    description: 'Global payments technology company operating the world largest electronic payments network.',
    basePrice: 280,
    currentPrice: 280,
    priceHistory: [{ turn: 0, price: 280 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.0075,
    beta: 1.0,
    splitMultiplier: 1,
  },
  {
    id: 'ma',
    ticker: 'MA',
    name: 'Mastercard Inc.',
    sector: 'financials',
    description: 'Global technology company in the payments industry connecting consumers, financial institutions, and merchants.',
    basePrice: 470,
    currentPrice: 470,
    priceHistory: [{ turn: 0, price: 470 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.006,
    beta: 1.0,
    splitMultiplier: 1,
  },
  {
    id: 'bac',
    ticker: 'BAC',
    name: 'Bank of America',
    sector: 'financials',
    description: 'One of the world largest financial institutions offering consumer banking, wealth management, and investment banking.',
    basePrice: 37,
    currentPrice: 37,
    priceHistory: [{ turn: 0, price: 37 }],
    volatility: 0.22,
    marketCap: 'mega',
    dividendYield: 0.028,
    beta: 1.15,
    splitMultiplier: 1,
  },
  {
    id: 'blk',
    ticker: 'BLK',
    name: 'BlackRock Inc.',
    sector: 'financials',
    description: 'World largest asset manager with over $10 trillion in AUM, operator of iShares ETFs and Aladdin platform.',
    basePrice: 820,
    currentPrice: 820,
    priceHistory: [{ turn: 0, price: 820 }],
    volatility: 0.2,
    marketCap: 'large',
    dividendYield: 0.025,
    beta: 1.0,
    splitMultiplier: 1,
  },
  {
    id: 'amzn',
    ticker: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: 'consumer',
    description: 'E-commerce giant and cloud computing leader (AWS) with expanding advertising and logistics businesses.',
    basePrice: 185,
    currentPrice: 185,
    priceHistory: [{ turn: 0, price: 185 }],
    volatility: 0.3,
    marketCap: 'mega',
    dividendYield: 0.0,
    beta: 1.2,
    splitMultiplier: 1,
  },
  {
    id: 'tsla',
    ticker: 'TSLA',
    name: 'Tesla Inc.',
    sector: 'consumer',
    description: 'Electric vehicle and clean energy company pioneering autonomous driving and energy storage.',
    basePrice: 250,
    currentPrice: 250,
    priceHistory: [{ turn: 0, price: 250 }],
    volatility: 0.5,
    marketCap: 'mega',
    dividendYield: 0.0,
    beta: 1.8,
    splitMultiplier: 1,
  },
  {
    id: 'nke',
    ticker: 'NKE',
    name: 'Nike Inc.',
    sector: 'consumer',
    description: 'Global athletic footwear, apparel, and equipment leader with strong brand loyalty worldwide.',
    basePrice: 100,
    currentPrice: 100,
    priceHistory: [{ turn: 0, price: 100 }],
    volatility: 0.25,
    marketCap: 'large',
    dividendYield: 0.014,
    beta: 1.1,
    splitMultiplier: 1,
  },
  {
    id: 'sbux',
    ticker: 'SBUX',
    name: 'Starbucks Corp.',
    sector: 'consumer',
    description: 'World largest coffeehouse chain operating thousands of stores across 80+ countries.',
    basePrice: 90,
    currentPrice: 90,
    priceHistory: [{ turn: 0, price: 90 }],
    volatility: 0.22,
    marketCap: 'large',
    dividendYield: 0.024,
    beta: 0.95,
    splitMultiplier: 1,
  },
  {
    id: 'mcd',
    ticker: 'MCD',
    name: "McDonald's Corp.",
    sector: 'consumer',
    description: 'Global fast-food restaurant chain and real estate company with 40,000+ locations worldwide.',
    basePrice: 295,
    currentPrice: 295,
    priceHistory: [{ turn: 0, price: 295 }],
    volatility: 0.14,
    marketCap: 'mega',
    dividendYield: 0.023,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'dis',
    ticker: 'DIS',
    name: 'Walt Disney Co.',
    sector: 'media',
    description: 'Global entertainment conglomerate spanning streaming (Disney+), parks, studios, and sports (ESPN).',
    basePrice: 112,
    currentPrice: 112,
    priceHistory: [{ turn: 0, price: 112 }],
    volatility: 0.28,
    marketCap: 'large',
    dividendYield: 0.0,
    beta: 1.1,
    splitMultiplier: 1,
  },
  {
    id: 'nflx',
    ticker: 'NFLX',
    name: 'Netflix Inc.',
    sector: 'media',
    description: 'Leading global streaming entertainment service with 250M+ subscribers and growing ad-supported tier.',
    basePrice: 630,
    currentPrice: 630,
    priceHistory: [{ turn: 0, price: 630 }],
    volatility: 0.35,
    marketCap: 'mega',
    dividendYield: 0.0,
    beta: 1.3,
    splitMultiplier: 1,
  },
  {
    id: 'wbd',
    ticker: 'WBD',
    name: 'Warner Bros. Discovery',
    sector: 'media',
    description: 'Media conglomerate combining HBO Max, Discovery+, and a vast film and TV content library.',
    basePrice: 12,
    currentPrice: 12,
    priceHistory: [{ turn: 0, price: 12 }],
    volatility: 0.4,
    marketCap: 'large',
    dividendYield: 0.0,
    beta: 1.2,
    splitMultiplier: 1,
  },
  {
    id: 'sony',
    ticker: 'SONY',
    name: 'Sony Group',
    sector: 'media',
    description: 'Japanese conglomerate with gaming (PlayStation), music, film, and semiconductor businesses.',
    basePrice: 88,
    currentPrice: 88,
    priceHistory: [{ turn: 0, price: 88 }],
    volatility: 0.24,
    marketCap: 'mega',
    dividendYield: 0.005,
    beta: 0.9,
    splitMultiplier: 1,
  },
  {
    id: 'ea',
    ticker: 'EA',
    name: 'Electronic Arts',
    sector: 'media',
    description: 'Major video game publisher known for EA Sports (FIFA/Madden), Battlefield, and Apex Legends franchises.',
    basePrice: 140,
    currentPrice: 140,
    priceHistory: [{ turn: 0, price: 140 }],
    volatility: 0.3,
    marketCap: 'large',
    dividendYield: 0.008,
    beta: 1.0,
    splitMultiplier: 1,
  },
  {
    id: 'cat',
    ticker: 'CAT',
    name: 'Caterpillar Inc.',
    sector: 'industrial',
    description: 'World largest construction and mining equipment manufacturer with a global dealer network.',
    basePrice: 350,
    currentPrice: 350,
    priceHistory: [{ turn: 0, price: 350 }],
    volatility: 0.22,
    marketCap: 'mega',
    dividendYield: 0.017,
    beta: 1.1,
    splitMultiplier: 1,
  },
  {
    id: 'ba',
    ticker: 'BA',
    name: 'Boeing Co.',
    sector: 'industrial',
    description: 'Aerospace company manufacturing commercial jets, defense systems, and space vehicles.',
    basePrice: 210,
    currentPrice: 210,
    priceHistory: [{ turn: 0, price: 210 }],
    volatility: 0.35,
    marketCap: 'large',
    dividendYield: 0.0,
    beta: 1.3,
    splitMultiplier: 1,
  },
  {
    id: 'hon',
    ticker: 'HON',
    name: 'Honeywell International',
    sector: 'industrial',
    description: 'Diversified industrial conglomerate in aerospace, building tech, performance materials, and safety.',
    basePrice: 200,
    currentPrice: 200,
    priceHistory: [{ turn: 0, price: 200 }],
    volatility: 0.16,
    marketCap: 'mega',
    dividendYield: 0.021,
    beta: 0.95,
    splitMultiplier: 1,
  },
  {
    id: 'ge',
    ticker: 'GE',
    name: 'GE Aerospace',
    sector: 'industrial',
    description: 'Aerospace company manufacturing jet engines and aviation systems, spun off from legacy GE conglomerate.',
    basePrice: 165,
    currentPrice: 165,
    priceHistory: [{ turn: 0, price: 165 }],
    volatility: 0.24,
    marketCap: 'large',
    dividendYield: 0.0,
    beta: 1.1,
    splitMultiplier: 1,
  },
  {
    id: 'lmt',
    ticker: 'LMT',
    name: 'Lockheed Martin',
    sector: 'industrial',
    description: 'Largest defense contractor specializing in fighter jets (F-35), missiles, and space systems.',
    basePrice: 460,
    currentPrice: 460,
    priceHistory: [{ turn: 0, price: 460 }],
    volatility: 0.16,
    marketCap: 'mega',
    dividendYield: 0.028,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'pld',
    ticker: 'PLD',
    name: 'Prologis Inc.',
    sector: 'realestate',
    description: 'Global leader in logistics real estate, owning and managing industrial warehouses for e-commerce.',
    basePrice: 130,
    currentPrice: 130,
    priceHistory: [{ turn: 0, price: 130 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.032,
    beta: 0.8,
    splitMultiplier: 1,
  },
  {
    id: 'amt',
    ticker: 'AMT',
    name: 'American Tower',
    sector: 'realestate',
    description: 'Global REIT owning and operating wireless and broadcast communications infrastructure.',
    basePrice: 200,
    currentPrice: 200,
    priceHistory: [{ turn: 0, price: 200 }],
    volatility: 0.2,
    marketCap: 'large',
    dividendYield: 0.038,
    beta: 0.75,
    splitMultiplier: 1,
  },
  {
    id: 'nee',
    ticker: 'NEE',
    name: 'NextEra Energy',
    sector: 'realestate',
    description: 'Largest utility company and world leader in wind and solar energy generation.',
    basePrice: 70,
    currentPrice: 70,
    priceHistory: [{ turn: 0, price: 70 }],
    volatility: 0.16,
    marketCap: 'mega',
    dividendYield: 0.028,
    beta: 0.65,
    splitMultiplier: 1,
  },
  {
    id: 'd',
    ticker: 'D',
    name: 'Dominion Energy',
    sector: 'realestate',
    description: 'Energy utility serving millions of customers with a growing renewable energy portfolio.',
    basePrice: 48,
    currentPrice: 48,
    priceHistory: [{ turn: 0, price: 48 }],
    volatility: 0.18,
    marketCap: 'large',
    dividendYield: 0.048,
    beta: 0.65,
    splitMultiplier: 1,
  },
  {
    id: 'so',
    ticker: 'SO',
    name: 'Southern Company',
    sector: 'realestate',
    description: 'Major US utility company providing electric and gas service with nuclear and renewable investments.',
    basePrice: 72,
    currentPrice: 72,
    priceHistory: [{ turn: 0, price: 72 }],
    volatility: 0.14,
    marketCap: 'large',
    dividendYield: 0.042,
    beta: 0.6,
    splitMultiplier: 1,
  },
  {
    id: 't',
    ticker: 'T',
    name: 'AT&T Inc.',
    sector: 'telecom',
    description: 'Telecom giant providing wireless, broadband, and fiber services to millions of US consumers.',
    basePrice: 18,
    currentPrice: 18,
    priceHistory: [{ turn: 0, price: 18 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.065,
    beta: 0.6,
    splitMultiplier: 1,
  },
  {
    id: 'vz',
    ticker: 'VZ',
    name: 'Verizon Comm.',
    sector: 'telecom',
    description: 'Major wireless carrier and broadband provider with nationwide 5G network coverage.',
    basePrice: 42,
    currentPrice: 42,
    priceHistory: [{ turn: 0, price: 42 }],
    volatility: 0.16,
    marketCap: 'mega',
    dividendYield: 0.065,
    beta: 0.55,
    splitMultiplier: 1,
  },
  {
    id: 'tmus',
    ticker: 'TMUS',
    name: 'T-Mobile US',
    sector: 'telecom',
    description: 'Fastest-growing US wireless carrier known for aggressive pricing and 5G leadership.',
    basePrice: 175,
    currentPrice: 175,
    priceHistory: [{ turn: 0, price: 175 }],
    volatility: 0.22,
    marketCap: 'mega',
    dividendYield: 0.0,
    beta: 0.7,
    splitMultiplier: 1,
  },
  {
    id: 'cmcsa',
    ticker: 'CMCSA',
    name: 'Comcast Corp.',
    sector: 'telecom',
    description: 'Media and telecom conglomerate operating Xfinity broadband, NBCUniversal, and Sky.',
    basePrice: 42,
    currentPrice: 42,
    priceHistory: [{ turn: 0, price: 42 }],
    volatility: 0.18,
    marketCap: 'mega',
    dividendYield: 0.026,
    beta: 0.85,
    splitMultiplier: 1,
  },
  {
    id: 'cme',
    ticker: 'CME',
    name: 'CME Group',
    sector: 'telecom',
    description: 'World largest financial derivatives exchange operator (Chicago Mercantile Exchange).',
    basePrice: 215,
    currentPrice: 215,
    priceHistory: [{ turn: 0, price: 215 }],
    volatility: 0.22,
    marketCap: 'large',
    dividendYield: 0.022,
    beta: 0.8,
    splitMultiplier: 1,
  },
  {
    id: 'lin',
    ticker: 'LIN',
    name: 'Linde PLC',
    sector: 'materials',
    description: 'World largest industrial gas company serving healthcare, manufacturing, and electronics.',
    basePrice: 440,
    currentPrice: 440,
    priceHistory: [{ turn: 0, price: 440 }],
    volatility: 0.16,
    marketCap: 'mega',
    dividendYield: 0.013,
    beta: 0.85,
    splitMultiplier: 1,
  },
  {
    id: 'nem',
    ticker: 'NEM',
    name: 'Newmont Corp.',
    sector: 'materials',
    description: 'World largest gold mining company with operations across multiple continents.',
    basePrice: 42,
    currentPrice: 42,
    priceHistory: [{ turn: 0, price: 42 }],
    volatility: 0.3,
    marketCap: 'large',
    dividendYield: 0.032,
    beta: 0.5,
    splitMultiplier: 1,
  },
  {
    id: 'fcx',
    ticker: 'FCX',
    name: 'Freeport-McMoRan',
    sector: 'materials',
    description: 'One of the world largest copper miners with significant gold and molybdenum operations.',
    basePrice: 42,
    currentPrice: 42,
    priceHistory: [{ turn: 0, price: 42 }],
    volatility: 0.35,
    marketCap: 'large',
    dividendYield: 0.024,
    beta: 1.2,
    splitMultiplier: 1,
  },
  {
    id: 'shw',
    ticker: 'SHW',
    name: 'Sherwin-Williams',
    sector: 'materials',
    description: 'Global leader in paint and coatings manufacturing for professional and retail markets.',
    basePrice: 310,
    currentPrice: 310,
    priceHistory: [{ turn: 0, price: 310 }],
    volatility: 0.18,
    marketCap: 'large',
    dividendYield: 0.008,
    beta: 0.85,
    splitMultiplier: 1,
  },
  {
    id: 'apd',
    ticker: 'APD',
    name: 'Air Products & Chemicals',
    sector: 'materials',
    description: 'Industrial gases company supplying hydrogen, helium, and atmospheric gases globally.',
    basePrice: 260,
    currentPrice: 260,
    priceHistory: [{ turn: 0, price: 260 }],
    volatility: 0.2,
    marketCap: 'large',
    dividendYield: 0.027,
    beta: 0.8,
    splitMultiplier: 1,
  },
];

export function cloneInitialStocks(): Stock[] {
  return INITIAL_STOCKS.map(s => ({
    ...s,
    currentPrice: s.basePrice,
    splitMultiplier: 1,
    priceHistory: [{ turn: 0, price: s.basePrice }],
  }));
}
